export default {
  roboto: {
    black: 'Roboto-Black',
    blackItalic: 'Roboto-BlackItalic',
    bold: 'Roboto-Bold',
    boldItalic: 'Roboto-BoldItalic',
    italic: 'Roboto-Italic',
    light: 'Roboto-Light',
    lightItalic: 'Roboto-LightItalic',
    medium: 'Roboto-Medium',
    mediumItalic: 'Roboto-MediumItalic',
    regular: 'Roboto-Regular',
    thin: 'Roboto-Thin',
    thinItalic: 'Roboto-ThinItalic',
  },
  urbanist: {
    black: 'Urbanist-Black',
    blackItalic: 'Urbanist-BlackItalic',
    bold: 'Urbanist-Bold',
    boldItalic: 'Urbanist-BoldItalic',
    italic: 'Urbanist-Italic',
    light: 'Urbanist-Light',
    lightItalic: 'Urbanist-LightItalic',
    medium: 'Urbanist-Medium',
    mediumItalic: 'Urbanist-MediumItalic',
    regular: 'Urbanist-Regular',
    thin: 'Urbanist-Thin',
    semiBold: 'Urbanist-SemiBold',
    semiBoldItalic: 'Urbanist-SemiBoldItalic',
    thinItalic: 'Urbanist-ThinItalic',
  },
};
